// Auto-generated by sync_contracts.py — do not edit.

use crate::contracts::LlmProvider;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmIpcClassifyRequest {
    pub text: String,
    pub scenario: Option<String>,
    pub options: Vec<String>,
    pub provider: Option<LlmProvider>,
    pub trace_id: Option<String>,
}
