[package]
name = "platform"
version.workspace = true
edition.workspace = true

[build-dependencies]
serde_json = { workspace = true }

[dependencies]
async-trait = { workspace = true }
base64 = "0.22"
common = { path = "../common" }
futures-util = { workspace = true }
md-5 = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rmpv = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
